### PR TITLE
Update the fork with latest upstream master

### PR DESCRIPTION
**Pull request by beyondbill**
Sync with https://github.com/poseidon/typhoon/commit/bf22222f7dbf929f8650698df6e9b845906fab22

### CODE REVIEW

**Comment by bendrucker** [comment]
Thank you! Will start reviewing this later today. Can do bootstrap now.

**Comment by beyondbill** [comment]
Created a new k8s cluster with the new typhoon
```terraform
locals {
  clc_snippets = list(templatefile("${path.module}/dockerd-config.yml.tpl", {
    max_log_file_size  = "100m"
    max_log_file_count = "2"
  }))
}

module "typhoon" {
  source = "git::https://github.com/takescoop/typhoon//aws/container-linux/kubernetes?ref=c70d4596"

  dns_zone          = "playground.takescoop.com"
  dns_zone_id       = "Z047455536YBYHITNAEA7"
  apiserver_aliases = ["kubernetes.playground.takescoop.com"]

  cluster_name = "typhoon-upgrade"

  controller_count = 2
  controller_type  = "t3.medium"
  worker_count     = 3
  worker_type      = "t3.medium"

  # https://typhoon.psdn.io/topics/performance/#network-performance
  network_mtu = 8981

  host_cidr = "10.10.48.0/20"

  bastion_clc_snippets = local.clc_snippets
  controller_snippets  = local.clc_snippets
  worker_snippets      = local.clc_snippets

  amis = {
    worker     = "ami-05042656a1c836c85"
    controller = "ami-05042656a1c836c85"
    bastion    = "ami-05042656a1c836c85"
  }

  ssh_user = "scoop-ops"

  apiserver_arguments = [
    "--oidc-issuer-url=https://accounts.google.com",
    "--oidc-client-id=462288329408-fm8iollojoc8fsmehbe31nqnjkekdb8m.apps.googleusercontent.com",
    "--oidc-username-claim=email",
  ]

  subnet_tags_public = {
    "a" = "b"
    "c" = "d"
  }

  subnet_tags_private = {
    "a" = "b"
    "c" = "d"
  }

  asset_dir = "output/typhoon-upgrade"
}
```

**Comment by beyondbill** [comment]
`module.typhoon.null_resource.bootstrap` failed. I did some debugging on the controller where the bootstrap ran. k8s apiserver wasn't serving port 443. `etcd` and `kubelet` failed to start. 
I'll appreciate a look from @bendrucker. You may run the following to see debugging logs:
```
➜  ~ ssh -A scoop-ops@bastion.typhoon-upgrade.playground.takescoop.com
Last login: Wed Apr 15 01:22:47 UTC 2020 from 71.198.152.89 on pts/0
Container Linux by CoreOS stable (1745.4.0)
Update Strategy: No Reboots
scoop-ops@ip-10-10-57-112 ~ $ ssh -A 10.10.56.174
Last login: Wed Apr 15 01:14:55 UTC 2020 from 10.10.57.112 on pts/2
Container Linux by CoreOS stable (1745.4.0)
Update Strategy: No Reboots
scoop-ops@ip-10-10-56-174 ~ $ sudo journalctl -u bootstrap.service
-- Logs begin at Wed 2020-04-15 01:06:40 UTC, end at Wed 2020-04-15 01:35:12 UTC. --
Apr 15 01:11:23 ip-10-10-56-174 systemd[1]: Starting Kubernetes control plane...
Apr 15 01:11:28 ip-10-10-56-174 rkt[1628]: [  288.594710] kubelet[6]: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean",
Apr 15 01:11:28 ip-10-10-56-174 rkt[1628]: [  288.595296] kubelet[6]: The connection to the server typhoon-upgrade.playground.takescoop.com:443 was refused - did you specify the right host or port?
Apr 15 01:11:28 ip-10-10-56-174 rkt[1628]: [  288.598921] kubelet[6]: Waiting for static pod control plane
Apr 15 01:11:33 ip-10-10-56-174 rkt[1628]: [  293.699967] kubelet[6]: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean",
Apr 15 01:11:33 ip-10-10-56-174 rkt[1628]: [  293.700914] kubelet[6]: The connection to the server typhoon-upgrade.playground.takescoop.com:443 was refused - did you specify the right host or port?
Apr 15 01:11:33 ip-10-10-56-174 rkt[1628]: [  293.704354] kubelet[6]: Waiting for static pod control plane
......

scoop-ops@ip-10-10-56-174 ~ $ sudo journalctl
/etcd
......
Apr 15 01:07:30 ip-10-10-56-174 systemd[1]: etcd-member.service: Main process exited, code=exited, status=254/n/a
Apr 15 01:07:30 ip-10-10-56-174 systemd[1]: etcd-member.service: Failed with result 'exit-code'.
Apr 15 01:07:31 ip-10-10-56-174 systemd[1]: Failed to start etcd (System Application Container).
......
/kublet
Apr 15 01:07:51 ip-10-10-56-174 systemd-timesyncd[689]: Timed out waiting for reply from 72.46.53.234:123 (1.coreos.pool.ntp.org).
Apr 15 01:08:01 ip-10-10-56-174 systemd-timesyncd[689]: Timed out waiting for reply from 64.62.190.177:123 (1.coreos.pool.ntp.org).
Apr 15 01:08:01 ip-10-10-56-174 rkt[1027]: run: Get https://quay.io/v2/: dial tcp 18.208.7.119:443: i/o timeout
Apr 15 01:08:01 ip-10-10-56-174 systemd[1]: kubelet.service: Main process exited, code=exited, status=254/n/a
Apr 15 01:08:01 ip-10-10-56-174 systemd[1]: kubelet.service: Failed with result 'exit-code'.
......
```

**Comment by bendrucker** [comment]
Got it, will have a look tomorrow

**Comment by bendrucker** [comment]
Thanks for the reminder, didn't get to this yesterday but will look today. If etcd fails to start that would be enough to break the rest so I'll start by looking at the logs for that service.

**Pull request merged**
